from scapy.all import sniff, IP, TCP, UDP, ARP, get_if_hwaddr, get_if_addr, conf
import requests
import threading
import time
from collections import defaultdict
import datetime
import socket

# Tracking window and settings
ANALYSIS_WINDOW_SEC = 5
API_URL = "http://localhost:8000/log"

# Find local IP simply to filter traffic generated by ourselves to the API, preventing infinite loops loops
try:
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    s.connect(("8.8.8.8", 80))
    LOCAL_IP = s.getsockname()[0]
    s.close()
except:
    LOCAL_IP = "127.0.0.1"

class DeviceState:
    def __init__(self):
        self.syn_sent = 0
        self.syn_ack_rcvd = 0
        self.fin_sent = 0
        self.dest_ips = set()
        self.dest_ports = set()
        self.dns_queries = 0

state_lock = threading.Lock()
stats = defaultdict(DeviceState)

# Helper function to categorize network limits roughly assuming typical local networks (192.x, 10.x)
def is_private_ip(ip_str):
    return ip_str.startswith("192.168.") or ip_str.startswith("10.") or ip_str.startswith("172.")

def packet_callback(packet):
    # Only process IP packets 
    if not IP in packet:
        return
        
    src_ip = packet[IP].src
    dst_ip = packet[IP].dst
    
    # Ignore loopback/backend API traffic 
    if dst_ip == "127.0.0.1" or (src_ip == LOCAL_IP and dst_ip == LOCAL_IP):
        return
    if TCP in packet and (packet[TCP].dport == 8000 or packet[TCP].sport == 8000):
        return
    if UDP in packet and (packet[UDP].dport == 8000 or packet[UDP].sport == 8000):
        return
        
    with state_lock:
        if is_private_ip(src_ip):
            st = stats[src_ip]
            st.dest_ips.add(dst_ip)
            
            # TCP Traffic
            if TCP in packet:
                st.dest_ports.add(packet[TCP].dport)
                flags = packet[TCP].flags
                if flags == "S":   # SYN
                    st.syn_sent += 1
                elif "F" in flags or "R" in flags: # FIN or RST implies end of session or failed session
                    st.fin_sent += 1
                    
            # DNS UDP queries
            elif UDP in packet and packet[UDP].dport == 53:
                st.dns_queries += 1

        # Track external replies verifying a successful connection (Half-open resolution)
        # If external server sends a SYN-ACK back to our private client, we know the handshake didn't fail
        if TCP in packet and packet[TCP].flags == "SA":
            if is_private_ip(dst_ip):
                stats[dst_ip].syn_ack_rcvd += 1


def network_analyzer_loop():
    """ Runs periodically to calculate Intent Scores and send to backend """
    while True:
        time.sleep(ANALYSIS_WINDOW_SEC)
        
        with state_lock:
            snap_stats = dict(stats)
            stats.clear() # Reset state for the next time window
            
        for ip, st in snap_stats.items():
            # Derive shadow intent heuristics 
            failed_ratio = max(0, st.syn_sent - st.syn_ack_rcvd) / float(st.syn_sent) if st.syn_sent > 0 else 0.0
            new_ips = len(st.dest_ips)
            port_div = len(st.dest_ports)
            dns_count = st.dns_queries
            
            # Rough approximation of short-session / half-open scans 
            # High volume of SYNs and FINs over a short burst without ACKs equates to short frequencies
            short_sess = (st.fin_sent + st.syn_sent) / 50.0 # Standardize to window bounds
            
            payload = {
                "device_id": ip,
                "failed_connection_ratio": failed_ratio,
                "new_dest_ip_attempts": new_ips,
                "port_diversity": port_div,
                "short_session_frequency": min(short_sess, 1.0),
                "suspicious_dns_queries": dns_count,
                "timestamp": datetime.datetime.now().isoformat()
            }
            
            try:
                # Post live device analytics array to FastAPI Backend
                requests.post(API_URL, json=payload, timeout=2)
            except requests.exceptions.RequestException:
                pass


if __name__ == '__main__':
    print(f"[*] Starting Real Local Network Sniffer (Local IP identified: {LOCAL_IP})")
    print(f"[*] Listening on primary interface '{conf.iface}'")
    print("[*] Filtering packets and transmitting aggregated device states to API...")
    
    # Start the reporting sub-thread
    analyzer_thread = threading.Thread(target=network_analyzer_loop, daemon=True)
    analyzer_thread.start()
    
    try:
        sniff(filter="ip", prn=packet_callback, store=0)
    except OSError as e:
        print(f"\n[ERROR] Failed to start packet capture: {e}")
        print("Note: On Windows, Scapy requires Npcap (https://npcap.com/) to be installed.")
        print("Please ensure Npcap is installed and running, or run the terminal as Administrator.")